### ISSUE TITLE
Failing to run cross-compiled windows executable: libssp-0.dll missing

### ISSUE THREAD

**Issue by bumi** [MagicalBitcoin/libtor-sys#30]
My cross-compiled Windows executable fails to run on Windows with a missing `libssp-0.dll` error.

I am cross-compiling the app from an Ubuntu system to Windows using:
```
$ cargo build --release --target=x86_64-pc-windows-gnu
```
The compilation works great but when I run the executable on Windows I get an error saying some `libssp-0.dll` is not found. 
So far it seems this error is related to the libtor dependency, but I am actually not very sure. 
Has anybody seen this before?

Code: https://github.com/getAlby/alby-companion-rs

**Comment by afilini** [comment]
Looking into it..

**Comment by afilini** [comment]
Try replacing `libtor-sys` in you project with the version from the pr and let me know what happens

**Comment by bumi** [comment]
oh wow. thanks! that looks good! The error is gone. 
I could not yet confirm that my app works as expected but it runs and no `libssp-0.dll` error! \o/

**Comment by afilini** [comment]
Awesome, will merge and make a new release then
