### ISSUE TITLE
Replace OpenSSL with Rustls

### ISSUE THREAD

**Issue by Mohsen7s** [MagicalBitcoin/libtor-sys#34]
Hi,

Is it possible to consider replacing opensll with rustls ?
If not, what about adding a feature which let us to switch to rustls ?

**Comment by afilini** [comment]
Hi, unfortunately that's not possible. Openssl is not used by the rust code, but by Tor itself (the C daemon). There's no way to replace it with rustls without making substantial changes to Tor.
