### ISSUE TITLE
Dirty Diff on Tor Dep

### ISSUE THREAD

**Issue by JeremyRubin** [MagicalBitcoin/libtor-sys#36]
I'm reviewing this library to see if it's something I want to run, and noticed that your directory differs from 0.4.6.9  on https://github.com/torproject/tor/tags
```diff
diff -r tor-src/configure.ac /Users/jr/Downloads/tor-tor-0.4.6.9/configure.ac
353d352
<   AC_SEARCH_LIBS(stdin, [fakestdio])
1362a1362,1374
> dnl ----------------------------------------------------------------------
> dnl Check if libcap is available for capabilities.
>
> tor_cap_pkg_debian="libcap2"
> tor_cap_pkg_redhat="libcap"
> tor_cap_devpkg_debian="libcap-dev"
> tor_cap_devpkg_redhat="libcap-devel"
>
> AC_CHECK_LIB([cap], [cap_init], [],
>   AC_MSG_NOTICE([Libcap was not found. Capabilities will not be usable.])
> )
> AC_CHECK_FUNCS(cap_set_proc)
>
diff -r tor-src/scripts/build/combine_libs /Users/jr/Downloads/tor-tor-0.4.6.9/scripts/build/combine_libs
29,34d28
<
<     # Delete the "__.SYMDEF SORTED" file if present, it will be generated
<     # by ranlib at the end on the combined library
<     if [ -f "__.SYMDEF SORTED" ]; then
<         rm -f "__.SYMDEF SORTED"
<     fi
diff -r tor-src/src/core/proto/include.am /Users/jr/Downloads/tor-tor-0.4.6.9/src/core/proto/include.am
5a6
> 	src/core/proto/proto_ext_or.c		\
diff -r tor-src/src/include.am /Users/jr/Downloads/tor-tor-0.4.6.9/src/include.am
89a90
> include src/tools/include.am
diff -r tor-src/src/lib/crypt_ops/crypto_openssl_mgt.h /Users/jr/Downloads/tor-tor-0.4.6.9/src/lib/crypt_ops/crypto_openssl_mgt.h
19d18
< #include <openssl/engine.h>
```

**Comment by afilini** [comment]
Yes, there are some patches that I have to apply to make it work, you can find them in the `patches/` directory.

In general the only differences should be the patches applied and the missing `Cargo.toml` files, because I don't need them (I disable the rust code in tor) and I remember I had some issues uploading a crate to crates.io with those `Cargo.toml` files inside, so I just deleted them.

In [`UPGRADE.md`](https://github.com/MagicalBitcoin/libtor-sys/blob/master/UPGRADE.md) you can find the commands I run whenever I upgrade tor or libevent.

**Comment by JeremyRubin** [comment]
It might make sense to run these patches during build.rs?

**Comment by afilini** [comment]
It's possible but I kinda wanted to avoid adding too many dependencies to the build process. That's why I patch locally and then run `autogen.sh` before publishing.

I would still have to remove the `Cargo.toml` files manually though, there's not much I can do for it.

**Comment by afilini** [comment]
Let me do some tests, the thing that's scaring me the most is compiling this under windows using cygwin/mingw. I have no experience with it whatsoever, I don't know if the environment provides all those tools.

An alternative once I move the source code to another crate would be to have one "vanilla" crate with everything just like the ofificial tor release, and one with the "pre patched" code, and you can pick which one to use through features. Ideally we would make the vanilla release the default on most platforms.

The `build.rs` of the vanilla crate would apply the patch, so it would be completely transparent for `libtor-sys`.

**Comment by JeremyRubin** [comment]
yeah i like that!

another note: git can apply patches, so in theory if git is a build dep already then you can use git to apply patch?
